# Generated by Django 4.2.5 on 2023-12-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('carrera', models.CharField(max_length=255)),
            ],
        ),
    ]
